#!/bin/bash

# file-info: простая программа получения информации о файле

#PROGNAME=$(basename $0)

file_info () {
		# file_info: функция для вывода информации о файле

		if [[ -e $1 ]]; then
				echo -e "\nFile Type:"
				file $1
				echo -e "\nFile Status:"
				stat $1
		else
				echo "$FUNCNAME: usage: $FUNCNAME file" >&2
				return 1
		fi
}