#!/bin/bash

# local-vars: сценарий, демонстрирующий локальные переменные

foo=0	# глобальная переменная foo

funct_1 () {
		local foo	# переменная foo, локальная для funct_1

		foo=1
		echo "funct_1: foo = $foo"
}

funct_2 () {
		local foo	# переменная foo, локальная для funct_2
		foo=2
		echo "funct_2: foo = $foo"
}

echo "global:  foo = $foo"
funct_1
echo "global:  foo = $foo"
funct_2
echo "global:  foo = $foo"