#!/bin/bash

# read-multiple: чтение нескольких значений с клавиатуры

echo -n "Echo one or move values > "
read var1 var2 var3 var4 var5

echo "var1 = '$var1'"
echo "var2 = '$var2'"
echo "var3 = '$var3'"
echo "var4 = '$var4'"
echo "var5 = '$var5'"