#!/bin/bash

# test-integer2: проверка целочисленного значения.

INT=-5

if [[ "$INT" =~ ^-?[0-9]+$ ]]; then
		if [ $INT -eq 0 ]; then
				echo "INT is zero."
		else
				if [ $INT -lt 0 ]; then
						echo "INT is negative."
				else
						echo "INT is possitive."
				fi
					if [ $((INT % 2)) -eq 0 ]; then
						echo "INT is even."
				else
						echo "INT is odd."
				fi
		fi
else
		echo "INT is not an answer." >&2
		exit 1
fi