#!/bin/bash

# test-string: проверка значения строки

ANSWER=yes

if [ -z "$ANSWER" ]; then
		echo "There is no answer." >&2
		exit 1
fi

if [ "$ANSWER" == "yes" ]; then
		echo "There answer is YES."
elif [ "$ANSWER" == "no" ]; then
		echo "The answer is NO."
elif [ "$ANSWER" == "maybe" ]; then
		echo "The answer is MAYBE."
else
		echo "The answer is UNKNOW."
fi