#!/bin/bash

echo "
Please Select:

1. Display System Information
2. Display Disk Space
3. Display Home Space Utilizatin
0. Quit
"
read -p "Enter selection [0-3] > "

if [[ $REPLY =~ ^[0-3]$ ]]; then
		if [[ $REPLY == 0 ]]; then
				echo "Program terminated."
		exit
		fi
else
		echo "Invalid entry." >&2
		exit 1
fi